version = 1

[[annotations]]
path = [
	"src/print.c",
	"src/print.h",
	"src/sunwait.c",
	"src/sunwait.h",
]
SPDX-FileCopyrightText = [
	"(c) 2000,2004,2022 Daniel Risacher",
	"Ian Craig (2012-13)",
]
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ["src/sunriset.c", "src/sunriset.h"]
SPDX-FileCopyrightText = [
	"(c) Paul Schlyter, 1989, 1992",
	"(c) 2000,2004,2022 Daniel Risacher",
]
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = [
	"tests/snapshot/**.txt",
]
SPDX-FileCopyrightText = "Copyright (C) 2025 Shota FUJI"
SPDX-License-Identifier = "GPL-3.0-only"
