// Copyright (C) 2025 Shota FUJI
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: GPL-3.0-only

= sunwait(1)
:docdate: 2025-07-20
:doctype: manpage
:mansource: sunwait

== Name

sunwait - Calculates sunrise or sunset times

== Synposis

*sunwait* [_options_] _<command>_ [_args_]

== Description

Sunwait calculates, displays, or waits for sunrise or sunset times at the given location.

See *sunwait-poll*(1), *sunwait-wait*(1), *sunwait-list*(1) and *sunwait-report*(1) for command specific document.

== Options

*--debug*::
	Prints debug logs. *wait* command exits in one minute if this option is set.

*--version*::
	Prints version number and exits.

*--help*::
	Prints help message to stdout and exits.

*--utc*::
	Prints and parses times in UTC timezone instead of local timzone.

*--lat* _<degree>_, *--latitude* _<degree>_::
_degree_ is a signed floating point number or a positive floating point number with N or S suffix.
Defaults to the latitude of Bingham, England.

*--lon* _<degree>_, *--longitude* _<degree>_::
_degree_ is a signed floating point number or a positive floating point number with E or W suffix.
Defaults to the longitude of Bingham, England.

*--twilight* _<type>_::
Sets a twilight type, which defines an angle of the Sun to consider twilight.
Valid values are:

* *daylight*      Top of the Sun just below (0 degrees) the horizon.
* *civil*         Civil twilight, top of the Sun 6 degrees below the horizon.
* *nautical*      Nautical twilight, top of the Sun 12 degrees below the horizon.
* *astronomical*  Astronomical twilight, top of the Sun 18 degrees below the horizon.
* _<degree>_        Custom angle as a floating point number. Can be negative.

*-o* _<duration>_, *--offset* _<duration>_::
Time offset to add to sunrise time and subtract from sunset time.
This offset value shifts sunrise and sunset time towards noon by the specified amount.
The value can be either of *MM* (minutes) or *HH:MM*, and can have hyphen to represent negative offset.

== Exit status

*0*    Command successfully ended.

*1*    Error, uncategorized or generic.

*10*   Out of memory.

*11*   Error during writing to stdout.

*12*   Error during writing to stderr.

*15*   Incorrect CLI usage, such as unknown option and invalid option value.

== See also

*sunwait-poll*(1), *sunwait-wait*(1), *sunwait-report*(1), *sunwait-list*(1)
