// Copyright (C) 2025 Shota FUJI
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: GPL-3.0-only

= sunwait-report(1)
:docdate: 2025-07-21
:doctype: manpage
:mansource: sunwait

== Name

sunwait-report - Prints detailed report of sunrise and sunset times for the date

== Synposis

*sunwait* *report* [*--date* _<YYYY-MM-DD>_]

== Description

This command prints detailed report on sunrise, sunset and other sun-related times for the date.

== Options

*--date* _<YYYY-MM-DD>_::
Calendar date to generate report for.
Defaults to the current date.

+
Each component must be 0 padded.
Missing a digit is a format error.

== Environment

*TZ*::
Generated report contains current timezone get by *localtime*(3) function, which refers to *TZ*.
If this variable is set, its value takes precedence over the system configured timezone.
See *tzset*(3) for timezone choosing algorithm.

== Examples

Produce a report of the different sunrises and sunsets on 2022/03/15 for Christmas Island, Australia.

[,shell]
----
sunwait report --date 2022-03-15 --lat 10.49S --lon 105.55E
----

== See also

*sunwait*(1)
