// Copyright (C) 2025 Shota FUJI
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: GPL-3.0-only

= sunwait-poll(1)
:docdate: 2025-07-20
:doctype: manpage
:mansource: sunwait

== Name

sunwait-poll - Prints whether it's day or night

== Synposis

*sunwait* *poll* [*--at* _<YYYY-MM-DDThh:mm:ssZ>_]

== Description

This command prints *DAY* or *NIGHT* depends on the current time and location, then exits with corresponding status.
Unlike normal program, this program never exits with status *0*.

== Options

*--at* _<YYYY-MM-DDThh:mm:ssZ>_::
Datetime to check day or night.
Defaults to the current time (system time).

+
You can omit parts after _DD_ entirely, as in *YYYY-MM-DD*.
In that case, time will be the start of the day.
For example, *--at 2020-01-01* is equivalent of *--at 2020-01-01T00:00:00*.

+
_Z_ is timezone offset notation in *hh*, *hh:mm*, or *Z* (UTC, means 00:00).
When timezone offset is not set, sunwait uses local timezone offset unless *--utc* option is set.

== Exit status

See *sunwait*(1) for error statuses.

*2*    It's day or twilight.

*3*    It' night (after twilight).

== Environment

*TZ*::
Value of *--at* option without timezone part will use the current timezone get by *timezone*(3) function.
If this variable is set, its value takes precedence over the system timezone.
See *tzset*(3) for timezone choosing algorithm.

== Examples

Prints it's DAY or NIGHT at Giza Necropolis.

[,shell]
----
sunwait poll --lat 29.977435N --lon 31.132484E
----

== See also

*sunwait*(1)
